services:
  postgres:
    image: postgres:15-alpine
    container_name: movies-crawler-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: movies_crawler
      POSTGRES_USER: movies_user
      POSTGRES_PASSWORD: movies_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - movies-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movies_user -d movies_crawler"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  movies-network:
    driver: bridge